# Generated by Django 4.2 on 2023-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
