# Generated by Django 4.2 on 2023-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_regi', '0005_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='profile_pics'),
        ),
    ]
