# Generated by Django 4.2 on 2023-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_regi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
    ]
